### ISSUE TITLE
System.Net.Http error

### ISSUE THREAD

**Issue by rgarofalo** [intuit/QuickBooks-V3-DotNET-SDK#116]
Hi,

I don't know why I keep getting this error
I installed version 8.1 via nuget, my project is with .net framework 4.6.1
Can anyone help me?

thanks

```
 threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Intuit.Ipp.OAuth2PlatformClient.DiscoveryClient..ctor(AppEnvironment appEnvironment)
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.GetDiscoveryDoc() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\OAuth2Client.cs:line 119
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client..ctor(String clientID, String clientSecret, String redirectURI, String environment) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\OAuth2Client.cs:line 88
```

**Comment by nimisha84** [comment]
Remove System.Net.Http and download it from Nuget package manager

**Comment by rgarofalo** [comment]
thanks
