### ISSUE TITLE
System.NullReferenceException in Intuit.Ipp.Core.CoreHelper.GetCompressor

### ISSUE THREAD

**Issue by ncrown** [intuit/QuickBooks-V3-DotNET-SDK#118]
Apologies for posting here, but I cannot seem to post a question on the developer site.  I keep hitting the 'Help redirect' page claiming I do not have a developer account.  Not sure how to complete that step...

Anyway, hoping someone here can help.

I'm getting the following stack when attempting to do my first call to fetch CompanyInfo.  Here is the call:

            QueryService<CompanyInfo> querySvc = new QueryService<CompanyInfo>(serviceContext);
            CompanyInfo companyInfo = querySvc.ExecuteIdsQuery($"SELECT * FROM CompanyInfo").FirstOrDefault();

Here is the stack:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Intuit.Ipp.Core.CoreHelper.GetCompressor(ServiceContext serviceContext, Boolean isRequest) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\CoreHelper.cs:line 136
   at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction[TResult](Func`1 func) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 587
   at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction(Action action) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 243
   at Intuit.Ipp.Core.Rest.SyncRestHandler.GetResponse(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 117
   at Intuit.Ipp.QueryFilter.QueryService`1.ExecuteIdsQuery(String idsQuery, QueryOperationType queryOperationType) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.QueryFilter\QueryService.cs:line 166

I'm setting the Compression/Serialization formats in code like so:

                context.IppConfiguration.Message.Request.CompressionFormat = Intuit.Ipp.Core.Configuration.CompressionFormat.GZip;
                context.IppConfiguration.Message.Request.SerializationFormat = Intuit.Ipp.Core.Configuration.SerializationFormat.Json;
                context.IppConfiguration.Message.Response.CompressionFormat = Intuit.Ipp.Core.Configuration.CompressionFormat.GZip;
                context.IppConfiguration.Message.Response.SerializationFormat = Intuit.Ipp.Core.Configuration.SerializationFormat.Json;

I'm likely doing something wrong on the initialization, so any help would be appreciated.

**Comment by rkasaraneni20** [comment]
Can you please post this and any future such questions which are API specific/realm specific on developer.intuit.com->help.
Please check if you can go to the company file and query this report on screen? Does it work or does it have issues too? 
Usually you get to see this error, when you are sending some null values in the request. Can you please send us request and response logs from your on the support ticket you create or can share the logs here.
Follow these steps to enable logging-
Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by ncrown** [comment]
@rkasaraneni20 - thank you for the pointers.  I've successfully connected and hit several APIs using a couple of the sample apps, so am now in the process of comparing the configuration between the two.  Thanks for the hat-tip on Fiddler.  I have wireshark, too, but that app is much simpler for http requests.
