### ISSUE TITLE
.net core 2.1/2.2 (Azure Functions) - Cannot create new ServiceContext

### ISSUE THREAD

**Issue by TrevorLinkgreen** [intuit/QuickBooks-V3-DotNET-SDK#120]
We are currently receiving the following stack trace when attempting to create a new ServiceContext in an Azure Function using .net core 2.2.  using the 9.6.1 version of the library

`
Object reference not set to an instance of an object.
`

```
at Intuit.Ipp.Core.ServiceContext..ctor(String appToken, String realmId, IntuitServicesType serviceType, IRequestValidator requestValidator)
   at Horticulture.ThirdParty.QuickBooks.Implementation.QuickBooksServiceContext.GetServiceContext(String accessToken) in QuickBooksServiceContext.cs:line 30
   at Horticulture.ThirdParty.QuickBooks.Implementation.QuickBooksInvoice.GetAllInvoices() in QuickBooksInvoice.cs:line 145
   at Functions.Financial.QuickBooksInvoicePush.Run(TimerInfo myTimer, ILogger log) in QuickBooksInvoicePush.cs:line 48"	
```

This is the code that we call to create the ServiceContext

````csharp
var appKey = _configurationService.GetValue(ConfigurationProperties.QuickBooksAppKey);
var realmId = _configurationService.GetValue(ConfigurationProperties.QuickBooksRealmId);
var appSecret = _configurationService.GetValue(ConfigurationProperties.QuickBooksAppSecret);
var discoveryUrl = _configurationService.GetValue(ConfigurationProperties.QuickBooksDiscoveryUrl);

var currentAccessToken = accessToken ?? _quickBooksAuthTokenService.GetAccessToken(appKey, appSecret, discoveryUrl);
var reqValidator = new OAuth2RequestValidator(currentAccessToken);

var serviceContext = new ServiceContext(appKey, realmId, IntuitServicesType.QBO, reqValidator);
````

The exception is thrown as soon as we attempt to create the ServiceContext.  No requests are visibly sent (in fiddler). 

Edit: formatting

**Comment by TrevorLinkgreen** [comment]
Reviewing test code shows that the 

````csharp
new ServiceContext(appKey, realmId, IntuitServicesType.QBO, reqValidator);
````
should NOT pass the appKey?

The following works
````csharp
new ServiceContext(realmId, IntuitServicesType.QBO, reqValidator);
````
