### ISSUE TITLE
NullReferenceException in GetCompressor

### ISSUE THREAD

**Issue by kramaswamy7** [intuit/QuickBooks-V3-DotNET-SDK#138]
Hi,

I'm regularly receiving the following exception:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Intuit.Ipp.Core.CoreHelper.GetCompressor(ServiceContext serviceContext, Boolean isRequest) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\CoreHelper.cs:line 136
   at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction[TResult](Func1 func) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 587
   at Intuit.Ipp.Core.Rest.SyncRestHandler.GetResponse(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 117
   at Intuit.Ipp.DataService.DataService.Update[T](T entity) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.DataService\DataService.cs:line 439`

The weirdness is that this exception is not always occurring. I cannot pin down exactly what causes it to happen, but what makes it even weirder is that when I run in debug mode, the exception never occurs. It seems to only occur when the code is being run in production, through a scheduler, and even at that, it seems to not always occur.

Any insights? I took a look at the code in question, and there seems to be no reason why that line would throw a NullReferenceException. For reference, I am using V14.0. I noticed V14.1 exists now, however, there doesn't seem to be any changes affecting this code, so I haven't updated yet.

Please let me know if there is something on my side that I need to be changing in order to prevent this exception from happening.

Thanks!

**Comment by nimisha84** [comment]
Yeah, there haven't been any changes for retry for a long time. When you did you start receiving this error? Did something change on your server? Can you enable serilog logging as mentioned in readme and I can look at those to then. I can fix the issue only when you or I can replicate this consistently.

**Comment by nimisha84** [comment]
Also, can you try to use Gzip compression or use no compression and see if that fixes your errors. I think deflate compression might not be causing issues with retries which are async in nature.

**Comment by kramaswamy7** [comment]
I will try those out and see if they help. Thanks!

**Comment by kramaswamy7** [comment]
Ah - was about to leave a comment on this one! Had removed it because I had added a few more testing things. Added Gzip compression and it looks like that *may* have worked, although I am still getting occasional errors. Will report back if there is more info.

**Comment by nimisha84** [comment]
oh ok, you can reopen this when you have the info then.

**Comment by kramaswamy7** [comment]
Hi Nimisha,

Got some more feedback. Not sure how to re-open the ticket, can you please do it from your end?

```
2020-08-06 13:58:53.6130 QuickbooksClient.QBOContext.IppConfiguration.Message.Request.CompressionFormat == GZip 
2020-08-06 13:58:53.7536 QuickbooksClient.QBOContext.IppConfiguration.Message.Response.CompressionFormat == GZip 
2020-08-06 13:58:55.0349 System.NullReferenceException: Object reference not set to an instance of an object.
at Intuit.Ipp.Core.CoreHelper.GetCompressor(ServiceContext serviceContext, Boolean isRequest) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\CoreHelper.cs:line 136
at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction[TResult](Func'1 func) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 587
at Intuit.Ipp.Core.Rest.SyncRestHandler.GetResponse(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 117
at Intuit.Ipp.DataService.DataService.Update[T](T entity) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.DataService\DataService.cs:line 439
```

So this time, as you suggested, I explicitly set the compression format to GZIP, as witnessed by the first two lines. Nonetheless the exception is still being thrown.

Line 136 in CoreHelper is contained within `case Configuration.CompressionFormat.Deflate`. That statement is evaluating to true despite the fact that, as witnessed above, the compression format for both `Request` and `Response` are set to GZip. 

I believe I have discovered at least part of the problem - namely, why it doesn't work by setting the compression formats explicitly. `IntuitRetryPolicy` has several constructors, one of which does not take a `ServiceContext` object (namely, `public IntuitRetryPolicy(int retryCount, TimeSpan retryInterval)`). If the `ServiceContext` object is not passed, I believe that it is using a default somehow, and that default does not have the settings that I specified in the initializer of the context earlier. I changed my initializer to pass the `ServiceContext` object, and now that error is no longer happening.

That being said - this could also just be another red herring. The error did indeed stop after I made the change, but the error wasn't necessarily consistently happening, so I might be back here again with another update :)

**Comment by kramaswamy7** [comment]
Okay - got some more info. After adding in the code mentioned previously, I now get the following exception instead:

```
Intuit.Ipp.Exception.RetryExceededException: The remote server returned an error: (401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Intuit.Ipp.Core.Rest.SyncRestHandler.CallRestService(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 269
   at Intuit.Ipp.Core.Rest.SyncRestHandler.<>c__DisplayClass6_0.b__0() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 119
   at Intuit.Ipp.Core.IntuitRetryPolicy.<>c__DisplayClass23_0.b__0() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 243
   at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction[TResult](Func`1 func) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 540
   --- End of inner exception stack trace ---
   at Intuit.Ipp.Exception.IdsExceptionManager.HandleException(IdsException idsException) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Exception\IdsExceptionManager.cs:line 43
   at Intuit.Ipp.DataService.DataService.Update[T](T entity) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.DataService\DataService.cs:line 443
```

Another, completely unrelated script I have, gives this error:

```
ERROR: Intuit.Ipp.Exception.RetryExceededException: The remote server returned an error: (401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.     
at System.Net.HttpWebRequest.GetResponse()     
at Intuit.Ipp.Core.Rest.SyncRestHandler.CallRestService(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 269     
at Intuit.Ipp.Core.Rest.SyncRestHandler.<>c__DisplayClass6_0.<GetResponse>b__0() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 119     at Intuit.Ipp.Core.IntuitRetryPolicy.<>c__DisplayClass23_0.<ExecuteAction>b__0() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 243     
at Intuit.Ipp.Core.IntuitRetryPolicy.ExecuteAction[TResult](Func`1 func) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Retry\IntuitRetryPolicy.cs:line 540     --- End of inner exception stack trace ---     at Intuit.Ipp.Exception.IdsExceptionManager.HandleException(IdsException idsException) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Exception\IdsExceptionManager.cs:line 43     
at Intuit.Ipp.DataService.Batch.Execute() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.DataService\Batch.cs:line 438
```

Both errors seem to have the same originating problem - the (401) Unauthorized exception.

The weird thing, though, is that there are requests prior to that which return successfully. The prior requests in the stack are all information fetching operations, though. So perhaps what is happening is an update requires higher permissions, which the executing agent doesn't have.

Is there any debugging info I could output that shows me what permissions the executing context has? I know that when I run this thing locally (using all the same connection properties, against the production environment), I have no problems.

**Comment by nimisha84** [comment]
Sorry, did not get the time to look into this issue. I will try to check what's going on in a day or two.

**Comment by nimisha84** [comment]
401 error generally means you token is expired for some reason. Other than that you always need admin permissions to a company to do OAuth2 and do all API operations using servicecontext.

**Comment by nimisha84** [comment]
Can you enable Serilogger and see what logs it generates? Or you can even use Fiddler to see what is happening with your retries?

**Comment by kramaswamy7** [comment]
The problem with both of those is that when I run the thing manually, it works perfectly fine - it's only when the server is running it automatically that it becomes a problem.

The permissions are definitely all properly set, which is why it works when I run it manually.

I will try enabling serilogger to see if I can get more log details. Will get back to you with more info.

**Comment by nimisha84** [comment]
Try leaving logs enabled on server as well. Get the rolling file or trace logs then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kramaswamy7** [comment]
Noticed you looking into this recently Nimisha - a few more insights from my side. I've tweaked the code around a bit - previously, there were two separate projects, one which handled the QBO sync process, and one which called it with info. I've merged the two together, and added more debugging steps to see if I can pin down exactly why the authorization is failing. I've also added a bit of a hacky step whereby if it detects a failed authorization, it first attempts to re-authorize and retry. I'll let you know if these work, or provide any other info at least.

**Comment by nimisha84** [comment]
Sure, please keep me posted. I actually marked this issue with hacktoberfest label so that any of the external devs or you too can look into the source code and fix this issue. There are swags to be won.

**Comment by kramaswamy7** [comment]
Hi Nimisha, got some more insights. Finally got it "working", by basically saying "if the original request fails because of 401 Unauthorized, try resetting the access token and trying again". Notice, though, that the access token at the initial call had an expiration of 7:40PM, whereas the one on the subsequent call is 9:23PM. I'm not sure why that would happen - I'm not re-requesting the token at each step. For some reason, though, it seems like the token is being reset - it's possible this is around the time where the token would have been expiring. Adding more logging to see if I can pin the problem down.

```
Starting GetCustomerByEmailAddress()
Access Token Expiration: 9/17/2020 7:40:40 PM
Starting GetCustomerByDisplayName()
Access Token Expiration: 9/17/2020 9:32:33 PM
Intuit.Ipp.Exception.RetryExceededException: The remote server returned an error: (401) Unauthorized. 
HandleException. Current attempt #: 0. Current exception: Intuit.Ipp.Exception.RetryExceededException
Resetting token to null.
Starting GetCustomerById()
Access Token Expiration: 9/17/2020 9:32:33 PM
```

**Comment by nimisha84** [comment]
Yes, access token changes every 1hr and that probably could the reason why you see a failure. Refresh token should be used to renew the access token when that happens

**Comment by kramaswamy7** [comment]
Some more insights:

```
Access Token Expiration: 9/18/2020 10:26:04 PM
Access Token Expired or Null. Re-issuing.
Access Token Expiration: 9/19/2020 4:30:42 AM
Intuit.Ipp.Exception.RetryExceededException
Resetting token to null. Current attempt #: 1.
Access Token Expired or Null. Re-issuing.
Access Token Expiration: 9/19/2020 4:30:43 AM
```

Notice that there is a one-second difference between the access token expiration. I wonder if there's some sort of time-delay problem? Maybe when the token is re-issued, and I make the next call, on your side the new token hasn't been registered yet?



11:30
WARN|CustomXolaReports.Jobs.Tasks.FlightAcademy.FlightAcademyQuickbooksOrderSync|Access Token Expiration: 9/19/2020 4:30:43 AM

**Comment by nimisha84** [comment]
@kramaswamy7 we have seen this issue with a short delay just after token refresh but haven't been able to consistently reproduce it.

**Comment by nimisha84** [comment]
Closing this old issue
