### ISSUE TITLE
Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by sdw283074970** [intuit/QuickBooks-V3-DotNET-SDK#51]
```c#
            var oauthValidator = new OAuth2RequestValidator(oauthInfo.AccessToken);
            var serviceContext = new ServiceContext(oauthInfo.RealmId, IntuitServicesType.QBO, oauthValidator);
            var dataService = new DataService(serviceContext);
            serviceContext.RequestId = GuidGenerator.GenerateGuid();

            var customer = new Customer {
                GivenName = "QQQ",
                Title = "WWW",
                MiddleName = "EEE",
                FamilyName = "AAA"
            };

            var result = dataService.Add(customer) as Customer;
```

Exception throw in the last line: Invalid URI: The format of the URI could not be determined.

StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Intuit.Ipp.Core.Rest.RestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId)
   at Intuit.Ipp.Core.Rest.SyncRestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId)
   at Intuit.Ipp.DataService.DataService.Add[T](T entity)
   at ClothResorting.Helpers.IntuitOAuthor.GetAllCustomer(String userId) in d:\users\downw\onedrive\documents\visual studio 2015\Projects\ClothResorting\ClothResorting\Helpers\IntuitOAuthor.cs:line 172
   at ClothResorting.Controllers.Api.QuickBooksOnlineOAuthController.SyncInvoiceToQBO(Int32 id) in d:\users\downw\onedrive\documents\visual studio 2015\Projects\ClothResorting\ClothResorting\Controllers\Api\QuickBooksOnlineOAuthController.cs:line 80
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

============
I have valid access_Token and successfully built `OAuth2RequestValidato` and `ServiceContext`. Is there any possibility that was caused by string encode? If so how could I fix it because I cannot touch the `Add()` method?

**Comment by sdw283074970** [comment]
By the way, the SDK version I am using is v5.6.0

**Comment by nimisha84** [comment]
Please enable logging in the code using Fiddler so that we can see the raw request and response data.
Steps below-
Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.
