### ISSUE TITLE
Current JsonReader item is not an object

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [intuit/QuickBooks-V3-DotNET-SDK#66]
I'm getting this error in y'alls code:
```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'Fault', line 1, position 29.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Intuit.Ipp.Utility.IntuitConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Intuit.Ipp.Utility.IntuitConverter.AssignValueToProperty(Object target, JProperty prop, Type type, String propName, JsonSerializer serializer)
   at Intuit.Ipp.Utility.IntuitConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intuit.Ipp.Utility.JsonObjectSerializer.Deserialize[T](String message)
   at Intuit.Ipp.DataService.Batch.Execute()
```
It started for certain company files of ours at 1AM PST this morning.

**Comment by nimisha84** [comment]
Can you enable fiddler logs or SDK logs to log raw req and response for this issue?
Fiddler -Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by ServicePal** [comment]
+1. We are seeing the same thing. 6x times since 6:51AM PST today.
Unfortunately, we do not have Azure logging in the PROD environment yet. And we do not get these errors in our TEST environment.

**Comment by nimisha84** [comment]
That's strange. I see it is an issue on Batch call originating from QBO v3 service as we did not change anything on SDK side. Unless I see the request and response, it is difficult for me to understand where the error is originating from.

**Comment by nimisha84** [comment]
Which SDK version are you on and what minoversion?

**Comment by Jesse-Hufstetler** [comment]
@nimisha84 It seems like it's gone away on its own. I observed it (coincidentally) on both 5.0.0.0 and 6.0.0. Now that it's not happening anymore I can't really get you the actual response. Here are some (all?) of the RealmIDs: `193514824011609`, `123146072801764`, `193514771950384`

I'm going to close the issue, I or @ServicePal can another issue (or re-open this one if that's allowed) if it comes back.

**Comment by ServicePal** [comment]
It went on all day yesterday and until this morning (around 1:25AM PST). Have not seen the errors since. Maybe Intuit can confirm this, but it seems there is API downtime (perhaps daily maintenance) around that time, almost every day.
