### ISSUE TITLE
Intuit.Ipp.Exception.SerializationException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [intuit/QuickBooks-V3-DotNET-SDK#67]
When I do
```csharp
reportService.ExecuteReport("AgedReceivables");
```
I get
```
Intuit.Ipp.Exception.SerializationException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Intuit.Ipp.Utility.ObjectToEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Intuit.Ipp.Utility.IntuitConverter.AssignValueToProperty(Object target, JProperty prop, Type type, String propName, JsonSerializer serializer)
   at Intuit.Ipp.Utility.IntuitConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Intuit.Ipp.Utility.IntuitConverter.AssignValueToProperty(Object target, JProperty prop, Type type, String propName, JsonSerializer serializer)
   at Intuit.Ipp.Utility.IntuitConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Intuit.Ipp.Utility.IntuitConverter.AssignValueToProperty(Object target, JProperty prop, Type type, String propName, JsonSerializer serializer)
   at Intuit.Ipp.Utility.IntuitConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intuit.Ipp.Utility.JsonObjectSerializer.Deserialize[T](String message)
   --- End of inner exception stack trace ---
   at Intuit.Ipp.Exception.IdsExceptionManager.HandleException(IdsException idsException)
   at Intuit.Ipp.Utility.JsonObjectSerializer.Deserialize[T](String message)
   at Intuit.Ipp.ReportService.ReportService.ExecuteReport(String reportName)
```

Happening on RealmId `193514831343224`

**Comment by nimisha84** [comment]
Can you please post this and any future such questions which are API specific/realm specific on developer.intuit.com->help.
Please check if you can go to the company file and query this report on screen? Does it work or does it have issues too? I will need additional logs from your on the support ticket you create.
Follow these steps to enable logging-
Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by Jesse-Hufstetler** [comment]
We don't have access to the company file that's doing this so I can't test within the app (we only have API keys). Using Fiddler I think I've identified the problem. It only happens every once in a while and only on certain company files. On Friday I was using [Linqpad](https://www.linqpad.net/) to run the `AgedReceivables` report and usually fiddler showed JSON like this (it has been slightly obfuscated to remove sensitive information):

```
{
    "Header":
    {
        "Time": "2019-02-18T07:51:04-08:00",
        "ReportName": "AgedReceivables",
        "DateMacro": "today",
        "StartPeriod": "2019-02-18",
        "EndPeriod": "2019-02-18",
        "Currency": "USD",
        "Customer": "111,222,333,444,555,666,777,888,999,123",
        "Option": [
        {
            "Name": "report_date",
            "Value": "2019-02-18"
        },
        {
            "Name": "NoReportData",
            "Value": "false"
        }]
    },
    "Columns":
    {
        "Column": [
        {
            "ColTitle": "",
            "ColType": "Customer"
        },
        {
            "ColTitle": "Current",
            "ColType": "Money"
        },
        {
            "ColTitle": "1 - 30",
            "ColType": "Money"
        },
        {
            "ColTitle": "31 - 60",
            "ColType": "Money"
        },
        {
            "ColTitle": "61 - 90",
            "ColType": "Money"
        },
        {
            "ColTitle": "91 and over",
            "ColType": "Money"
        },
        {
            "ColTitle": "Total",
            "ColType": "Money"
        }]
    },
    "Rows":
    {
        "Row": [
        {
            "ColData": [
            {
                "value": "Something Something Something",
                "id": "111"
            },
            {
                "value": "12.34"
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": "12.34"
            }]
        },
        {
            "ColData": [
            {
                "value": "Someone Someone Someone",
                "id": "222"
            },
            {
                "value": "23.45"
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": ""
            },
            {
                "value": "23.45"
            }]
        },
        {
            "Summary":
            {
                "ColData": [
                {
                    "value": "TOTAL"
                },
                {
                    "value": "35.79"
                },
                {
                    "value": "0.00"
                },
                {
                    "value": "0.00"
                },
                {
                    "value": "0.00"
                },
                {
                    "value": "0.00"
                },
                {
                    "value": "35.79"
                }]
            },
            "type": "Section",
            "group": "GrandTotal"
        }]
    }
}
```

But every third time or so that I ran the code the server would return something like this:

```
{
    "Header":
    {
        "Time": "2019-02-15T13:06:34-08:00",
        "ReportName": "AgedReceivables",
        "DateMacro": "today",
        "ReportBasis": null,
        "StartPeriod": "2019-02-15",
        "EndPeriod": "2019-02-15",
        "SummarizeColumnsBy": null,
        "Currency": "USD",
        "Customer": "111,222,333,444,555,666,777,888,999,123",
        "Vendor": null,
        "Employee": null,
        "Item": null,
        "Class": null,
        "Department": null,
        "Option": [
        {
            "Name": "report_date",
            "Value": "2019-02-15"
        },
        {
            "Name": "NoReportData",
            "Value": "false"
        }]
    },
    "Columns":
    {
        "Column": [
        {
            "ColTitle": "",
            "ColType": "Customer",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "Current",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "1 - 30",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "31 - 60",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "61 - 90",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "91 and over",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        },
        {
            "ColTitle": "Total",
            "ColType": "Money",
            "MetaData": null,
            "Columns": null
        }]
    },
    "Rows":
    {
        "Row": [
        {
            "id": null,
            "parentId": null,
            "Header": null,
            "Rows": null,
            "Summary": null,
            "ColData": [
            {
                "Attributes": null,
                "value": "Something Something Something",
                "id": "123",
                "href": null
            },
            {
                "Attributes": null,
                "value": "12.34",
                "id": null,
                "href": null
            },
            {
                "Attributes": null,
                "value": "",
                "id": null,
                "href": null
            },
            {
                "Attributes": null,
                "value": "",
                "id": null,
                "href": null
            },
            {
                "Attributes": null,
                "value": "",
                "id": null,
                "href": null
            },
            {
                "Attributes": null,
                "value": "",
                "id": null,
                "href": null
            },
            {
                "Attributes": null,
                "value": "12.34",
                "id": null,
                "href": null
            }],
            "type": null,
            "group": null
        },
        {
            "id": null,
            "parentId": null,
            "Header": null,
            "Rows": null,
            "Summary":
            {
                "ColData": [
                {
                    "Attributes": null,
                    "value": "TOTAL",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "12.34",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "0.00",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "0.00",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "0.00",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "0.00",
                    "id": null,
                    "href": null
                },
                {
                    "Attributes": null,
                    "value": "12.34",
                    "id": null,
                    "href": null
                }]
            },
            "ColData": null,
            "type": "Section",
            "group": "GrandTotal"
        }]
    }
}
```

*The fact that there's two columns in the good data and one column in the bad data is not relevant, it's probably because the bad data came from friday when the error was happening and the good data came from today, and the error is no longer happening today.*

You can even recreate the error yourself in C# like this:
```
var json = "{\"Header\":{\"Time\":\"2019-02-15T13:06:34-08:00\",\"ReportName\":\"AgedReceivables\",\"Dat" +
    "eMacro\":\"today\",\"ReportBasis\":null,\"StartPeriod\":\"2019-02-15\",\"EndPeriod\":\"2019-" +
    "02-15\",\"SummarizeColumnsBy\":null,\"Currency\":\"USD\",\"Customer\":\"242,695,459,243,13" +
    "0,244,245,599,246,247\",\"Vendor\":null,\"Employee\":null,\"Item\":null,\"Class\":null,\"D" +
    "epartment\":null,\"Option\":[{\"Name\":\"report_date\",\"Value\":\"2019-02-15\"},{\"Name\":\"N" +
    "oReportData\",\"Value\":\"false\"}]},\"Columns\":{\"Column\":[{\"ColTitle\":\"\",\"ColType\":\"C" +
    "ustomer\",\"MetaData\":null,\"Columns\":null},{\"ColTitle\":\"Current\",\"ColType\":\"Money\"" +
    ",\"MetaData\":null,\"Columns\":null},{\"ColTitle\":\"1 - 30\",\"ColType\":\"Money\",\"MetaDat" +
    "a\":null,\"Columns\":null},{\"ColTitle\":\"31 - 60\",\"ColType\":\"Money\",\"MetaData\":null," +
    "\"Columns\":null},{\"ColTitle\":\"61 - 90\",\"ColType\":\"Money\",\"MetaData\":null,\"Columns" +
    "\":null},{\"ColTitle\":\"91 and over\",\"ColType\":\"Money\",\"MetaData\":null,\"Columns\":nu" +
    "ll},{\"ColTitle\":\"Total\",\"ColType\":\"Money\",\"MetaData\":null,\"Columns\":null}]},\"Row" +
    "s\":{\"Row\":[{\"id\":null,\"parentId\":null,\"Header\":null,\"Rows\":null,\"Summary\":null,\"" +
    "ColData\":[{\"Attributes\":null,\"value\":\"Landmark Missionary Baptist Church\",\"id\":\"" +
    "695\",\"href\":null},{\"Attributes\":null,\"value\":\"24.99\",\"id\":null,\"href\":null},{\"At" +
    "tributes\":null,\"value\":\"\",\"id\":null,\"href\":null},{\"Attributes\":null,\"value\":\"\",\"" +
    "id\":null,\"href\":null},{\"Attributes\":null,\"value\":\"\",\"id\":null,\"href\":null},{\"Att" +
    "ributes\":null,\"value\":\"\",\"id\":null,\"href\":null},{\"Attributes\":null,\"value\":\"24.9" +
    "9\",\"id\":null,\"href\":null}],\"type\":null,\"group\":null},{\"id\":null,\"parentId\":null," +
    "\"Header\":null,\"Rows\":null,\"Summary\":{\"ColData\":[{\"Attributes\":null,\"value\":\"TOTA" +
    "L\",\"id\":null,\"href\":null},{\"Attributes\":null,\"value\":\"24.99\",\"id\":null,\"href\":nu" +
    "ll},{\"Attributes\":null,\"value\":\"0.00\",\"id\":null,\"href\":null},{\"Attributes\":null," +
    "\"value\":\"0.00\",\"id\":null,\"href\":null},{\"Attributes\":null,\"value\":\"0.00\",\"id\":nul" +
    "l,\"href\":null},{\"Attributes\":null,\"value\":\"0.00\",\"id\":null,\"href\":null},{\"Attrib" +
    "utes\":null,\"value\":\"24.99\",\"id\":null,\"href\":null}]},\"ColData\":null,\"type\":\"Secti" +
    "on\",\"group\":\"GrandTotal\"}]}}";
var jos = new JsonObjectSerializer();
jos.Deserialize<Report>(json).Dump();
```

**Comment by nimisha84** [comment]
Yeah, I do a see other diff like null values being received in response for many fields. I suspect some billing issue or data corruption or our server issues.
Can you share some realmids and the time around which you saw these errors? Do you still get them randomly for any of your companies?

**Comment by nimisha84** [comment]
Since this is company specific info, please create a support ticket and add the ticket num here. I will followup on that one.

**Comment by Jesse-Hufstetler** [comment]
It was happening right when I made the issue, so Feb 15 9AM EST. I only remember it happening for that one realm ID.

**Comment by Jesse-Hufstetler** [comment]
I opened a support ticket, it's case number 00075309

**Comment by nimisha84** [comment]
Tracking your case on the ticket. Please respond for the additional data asked
