### ISSUE TITLE
Cannot instantiate ServiceContext in .NET 4.6.1

### ISSUE THREAD

**Issue by mayankparmar2000** [intuit/QuickBooks-V3-DotNET-SDK#80]
`Dim oauthValidator As New OAuth2RequestValidator(accessToken)
 Dim context As New ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator)`

I have copied this code from sample, if I run my sample project it works fine, but not in my main project. I have checked there is nothing defined in web.config in sample project. I am not sure what should be the path. And in sample project also there is no such path defined, but it works fine.

I face below error :
`Please specify a valid directory path.

Attempted to access a path that is not on the disk.

at Intuit.Ipp.Core.Configuration.LocalConfigReader.ReadConfiguration() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\Configuration\LocalConfigReader.cs:line 165
   at Intuit.Ipp.Core.ServiceContext..ctor() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\ServiceContext.cs:line 204
   at Intuit.Ipp.Core.ServiceContext..ctor(String realmId, IntuitServicesType serviceType, IRequestValidator requestValidator) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\ServiceContext.cs:line 133
`

**Comment by mayankparmar2000** [comment]
I got it fixed using below changes in web.config

`<logger>
        
        <requestLog enableRequestResponseLogging="true" requestResponseLoggingDirectory="D:\Data\Projects\The Importer\The Importer For Developer\TheImporter\DataBank\IPPLogs" />
        <customLogger name="traceLogger" type="Intuit.Ipp.Diagnostics.TraceLogger, Intuit.Ipp.Diagnostics, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" enable="true" />
        
      </logger>`
